### ISSUE TITLE
panic

### ISSUE THREAD

**Issue by zhoushoujianwork** [xops-infra/jms#18]
![image](https://github.com/user-attachments/assets/f8055183-873e-485a-b7f2-d888cc9ce79f)
`2024-11-06T02:02:12.665Z	[34mINFO[0m	instance/server.go:48	get instances profile: tencent-hub len: 284
2024-11-06T02:02:14.349Z	[34mINFO[0m	instance/server.go:48	get instances profile: aws-us0066 len: 309
2024-11-06T02:02:18.206Z	[34mINFO[0m	instance/server.go:48	get instances profile: tx-cn-stage len: 428
2024-11-06T02:02:18.698Z	[34mINFO[0m	instance/server.go:48	get instances profile: cn9554 len: 441
2024-11-06T02:02:18.800Z	[34mINFO[0m	instance/server.go:48	get instances profile: cn0536 len: 441
2024-11-06T02:02:21.127Z	[34mINFO[0m	instance/server.go:48	get instances profile: us1549 len: 552
2024-11-06T02:02:24.296Z	[34mINFO[0m	instance/server.go:48	get instances profile: us/us7478 len: 665
2024-11-06T02:02:24.623Z	[34mINFO[0m	instance/server.go:48	get instances profile: aws-cn3977 len: 716
2024-11-06T02:02:25.737Z	[34mINFO[0m	instance/server.go:48	get instances profile: tx-cn-it len: 725
2024-11-06T02:02:30.004Z	[34mINFO[0m	app/state.go:117	success load mcs
2024-11-06T02:02:30.406Z	[34mINFO[0m	cmd/sshd.go:195	user: gulingwei, remote addr: 10.0.16.2:51827 login success
[LC_TERMINAL_VERSION=3.4.8 LANG=zh_CN.UTF-8 LC_TERMINAL=iTerm2] 10.0.16.2:51827
2024-11-06T02:02:38.718Z	[34mINFO[0m	cmd/sshd.go:195	user: lianbin, remote addr: 10.0.18.2:7280 login success
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x1ce34a9]

goroutine 133761 [running]:
github.com/chzyer/readline.(*opSearch).ExitSearchMode(0xc01c92d5e0?, 0x88?)
	/Users/mikas/go/pkg/mod/github.com/chzyer/readline@v1.5.1/search.go:118 +0x49
github.com/chzyer/readline.(*Operation).ioloop(0xc01c92d5e0)
	/Users/mikas/go/pkg/mod/github.com/chzyer/readline@v1.5.1/operation.go:304 +0x7c6
created by github.com/chzyer/readline.NewOperation in goroutine 133693
	/Users/mikas/go/pkg/mod/github.com/chzyer/readline@v1.5.1/operation.go:88 +0x2d6`

**Comment by zhoushoujianwork** [comment]
![image](https://github.com/user-attachments/assets/bb4499f8-e18e-4519-9979-265820d6882c)
复现
